apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kpkn11yc0-java-springboot
  janus-idp.io/tekton: kpkn11yc0-java-springboot
  backstage.io/kubernetes-id: kpkn11yc0-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: kpkn11yc0-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
